package com.MomentumInvestments.MomentumInvestmentsApplication.dto.Request;

public record InvestorCreation(
        String name,
        String surname,
        String dateOfBirth,
        String address,
        String phoneNumber,
        String email,
        String password
) {
    // No need for explicit getter methods, they are auto-generated by the record
}
